// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip buttonSound;	
		public AudioClip winSound;
		public AudioClip looseSound;
        public AudioClip bounce;
        public AudioClip bounceSpawn;

    }
}